version: "3.9"

services:

    web:
        
        container_name: tea_web
        image: tea/web

        entrypoint: "apachectl -D FOREGROUND"

        depends_on: 
        - db
            
        expose: 
        - "80"
        
        #hostPort:containerPort
        ports:
        - 8080:80

        volumes: 

        #document root for webserver
        - ../frontend/dist/:${DOCUMENT_ROOT}/frontend
        - ../backend/:${DOCUMENT_ROOT}/backend      
                
        #sync host machine timezone with container
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"

        #Apache global and vhost settings
        - ./apache2/apache2.conf:/etc/apache2/apache2.conf 
        - ./apache2/sites-available/lmc.conf:/etc/apache2/sites-available/lmc.conf 

        # On build setup - this script runs inside the container and is triggered by the run.sh script
        - ./apache2/docker-onbuild.sh:/docker-onbuild.sh  
 
        #log
        - ./log/apache2:/var/log/apache2

        environment: 
            DOCUMENT_ROOT: ${DOCUMENT_ROOT}
            BACKEND_ROOT: ${BACKEND_ROOT}
            DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}     
            STATIC_ROOT: ${STATIC_ROOT}    
            WSGIDIR: ${WSGIDIR}
            WSGIFILE: ${WSGIFILE}

            #Make the database credentils available to django to enable access the database
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASSWORD: ${DB_PASSWORD}


    db:
        container_name: tea_db
        image: tea/db

        environment:

            #postgres expects these envirnment variables to be set.
            #these are PostGres specific. Others will vary
            PGPORT: ${DB_PORT}
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD} 


        ports: 
        - ${DB_PORT}:${DB_PORT}

        volumes: 
        - tea_dbdata:/var/lib/postgresql/data    
    
volumes: 
    tea_dbdata :
