# Generated by Django 3.2.6 on 2021-11-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.TextField(help_text='Provide a name for your team', verbose_name='Name of the team')),
            ],
        ),
        migrations.CreateModel(
            name='Team_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='First name')),
                ('surname', models.TextField(verbose_name='Surname')),
                ('skill_level', models.PositiveIntegerField(choices=[(1, 'Junior'), (1, 'Intermediate'), (3, 'Senior')], default=1, max_length=1)),
            ],
            options={
                'verbose_name': 'Team member',
                'verbose_name_plural': 'Team members',
                'ordering': [],
            },
        ),
    ]
