# Generated by Django 3.2.6 on 2021-11-10 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teams',
        ),
    ]
