# Generated by Django 3.2.6 on 2021-11-10 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamaker', '0002_rename_team_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_members',
            name='team',
            field=models.ForeignKey(default=None, help_text='Which team does this member belong to?', on_delete=django.db.models.deletion.CASCADE, to='teamaker.teams', verbose_name='Name of team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='team_description',
            field=models.TextField(default=1, help_text='A short blurb about the team', verbose_name='Describe the team'),
            preserve_default=False,
        ),
    ]
