# Generated by Django 3.2.6 on 2021-11-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamaker', '0004_alter_teams_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', help_text='Not used', max_length=1, null=True),
        ),
    ]
