# Generated by Django 3.2.6 on 2021-11-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamaker', '0005_auto_20211111_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skill_level',
            field=models.PositiveIntegerField(choices=[(1, 'Junior'), (2, 'Intermediate'), (3, 'Senior')], default=1),
        ),
    ]
